dubbo:
  scan:
    base-packages: com.exam.alipay.service

  protocol:
    name: dubbo
    port: 3057
  registry:
    address: nacos://47.106.179.74:8848
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.179.74:8848